-- [파일 역할] Flyway 1번 마이그레이션: 처음 테이블 4개(roles, rooms, room_players, room_actions)를 만들고 직업 사전을 채운다.
--   Flyway는 파일 이름의 V1, V2, V3 순서로 한 번씩만 실행하고 flyway_schema_history 테이블에 기록한다.
--   이미 적용된 이 파일을 고치면 체크섬이 달라져 서버 시작이 실패한다. 변경은 항상 새 V 파일로.
-- 원본 위치: server/src/main/resources/db/migration/V1__create_role_api_tables.sql

-- 공개 직업 사전. 새 직업은 추후 V2 등 새 Flyway 마이그레이션으로 추가한다.
CREATE TABLE roles (
    code VARCHAR(60) PRIMARY KEY,       -- 직업 코드(예: CREW_CAPTAIN). 문자열 PK
    name VARCHAR(100) NOT NULL,         -- 한글 이름
    faction VARCHAR(20) NOT NULL,       -- 진영(CREW/PIRATE/NEUTRAL) 문자열
    action_code VARCHAR(40)             -- 능력 코드. 능력이 없으면 NULL
);

-- 게임(방). 공개 API에서는 gamesId라고 부른다.
CREATE TABLE rooms (
    -- GENERATED BY DEFAULT AS IDENTITY: 값을 안 넣으면 DB가 1, 2, 3... 자동 부여 (JPA의 IDENTITY 전략과 짝)
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phase VARCHAR(20) NOT NULL,         -- 현재 단계(SETUP/DAY/NIGHT/...)
    night_number INTEGER NOT NULL       -- 라운드 번호
);

-- user_id는 계정 ID, player_id는 방에서만 유효한 플레이어 번호다.
CREATE TABLE room_players (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- 내부 PK
    room_id BIGINT NOT NULL REFERENCES rooms(id),           -- 외래키: 반드시 존재하는 방이어야 함
    user_id BIGINT NOT NULL,                                -- 계정 번호(JWT sub)
    player_id BIGINT NOT NULL,                              -- 방 안 번호
    role_code VARCHAR(60) REFERENCES roles(code),           -- 외래키: 사전에 있는 직업만. 배정 전이면 NULL
    alive BOOLEAN NOT NULL,                                 -- 생존 여부
    remaining_uses INTEGER NOT NULL,                        -- 남은 능력 횟수 (→ V2에서 삭제됨: 기록에서 세는 방식으로 변경)
    CONSTRAINT uq_room_user UNIQUE (room_id, user_id),      -- 한 방에 같은 계정 중복 금지
    CONSTRAINT uq_room_player UNIQUE (room_id, player_id)   -- 한 방에 같은 번호 중복 금지
);

-- request_id 재시도와 night_number당 한 번 제출을 DB 제약으로도 보장한다.
CREATE TABLE room_actions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- 행동 PK
    room_id BIGINT NOT NULL REFERENCES rooms(id),           -- 방 외래키
    actor_player_id BIGINT NOT NULL,                        -- 행동한 사람
    night_number INTEGER NOT NULL,                          -- 몇 번째 밤 (→ V2에서 round_number로 대체)
    request_id UUID NOT NULL,                               -- 재시도 판별용 요청 ID
    action_code VARCHAR(40) NOT NULL,                       -- 능력 코드
    target_player_id BIGINT NOT NULL,                       -- 대상
    status VARCHAR(20) NOT NULL,                            -- SUBMITTED / RESOLVED
    CONSTRAINT uq_action_request UNIQUE (room_id, actor_player_id, request_id), -- 같은 요청 두 번 저장 금지
    CONSTRAINT uq_action_night UNIQUE (room_id, actor_player_id, night_number)  -- 한 밤에 한 번 (→ V2에서 교체)
);

-- 최초 직업 사전. 이때는 선의만 능력이 있었고, 나머지는 V2에서 능력이 붙는다.
INSERT INTO roles (code, name, faction, action_code) VALUES
    ('CREW_CAPTAIN', '선장', 'CREW', NULL),
    ('CREW_DOCTOR', '선의', 'CREW', 'PROTECT'),
    ('CREW_LOOKOUT', '망루지기', 'CREW', NULL),
    ('CREW_BOATSWAIN', '갑판장', 'CREW', NULL),
    ('CREW_GUNNER', '총잡이', 'CREW', NULL),        -- V2에서 이름이 '포수'로 바뀐다
    ('CREW_DRUNK', '주정뱅이', 'CREW', NULL),
    ('CREW_GHOST', '유령 선원', 'CREW', NULL),      -- V2에서 비활성화
    ('PIRATE_RAIDER', '해적', 'PIRATE', NULL),
    ('PIRATE_KRAKEN', '크라켄', 'PIRATE', NULL),    -- V2에서 비활성화
    ('PIRATE_SPY', '스파이', 'PIRATE', NULL),       -- V2에서 비활성화
    ('NEUTRAL_MONKEY', '원숭이', 'NEUTRAL', NULL);  -- V2에서 비활성화(새 원숭이는 CREW_MONKEY)
