-- [파일 역할] Flyway 2번 마이그레이션: 직업 활성/비활성, 능력 연결, 원숭이 위장 컬럼, 승리 컬럼,
--   행동 테이블의 "밤 번호" → "단계 + 라운드" 구조 변경, 보고 테이블 생성.
--   V1을 고치지 않고 ALTER로 바꾼 이유: 이미 V1이 적용된 DB도 안전하게 따라오게 하려고.
-- 원본 위치: server/src/main/resources/db/migration/V2__active_roles_and_actions.sql

-- 보류 직업은 기존 참조를 보존하면서 새 게임의 직업 목록에서 제외한다.
ALTER TABLE roles ADD COLUMN enabled BOOLEAN NOT NULL DEFAULT TRUE; -- 기존 행은 기본값 TRUE로 채워진다
UPDATE roles SET enabled = FALSE WHERE code IN
    ('PIRATE_KRAKEN', 'PIRATE_SPY', 'CREW_GHOST', 'NEUTRAL_MONKEY'); -- 4개 비활성화 (삭제하지 않음: FK 참조 보존)

-- 직업마다 능력 코드 연결 (ActionCode enum 이름과 같아야 한다)
UPDATE roles SET action_code = 'INVESTIGATE_FACTION' WHERE code = 'CREW_CAPTAIN';
UPDATE roles SET action_code = 'WATCH_VISITORS' WHERE code = 'CREW_LOOKOUT';
UPDATE roles SET action_code = 'BLOCK' WHERE code = 'CREW_BOATSWAIN';
UPDATE roles SET name = '포수', action_code = 'DAY_SHOOT' WHERE code = 'CREW_GUNNER'; -- 이름도 변경
UPDATE roles SET action_code = 'READ_CORPSE_ROLE' WHERE code = 'CREW_DRUNK';
UPDATE roles SET action_code = 'TEAM_ATTACK_VOTE' WHERE code = 'PIRATE_RAIDER'; -- 옛 방식(→ V3에서 SELECT_ATTACK_TARGET으로 교체)

-- 새 직업 3개 추가. 원숭이는 이제 선원 진영이고 능력은 위장 직업 것을 쓰므로 action_code가 NULL.
INSERT INTO roles (code, name, faction, action_code, enabled) VALUES
    ('CREW_SAILOR', '일반 선원', 'CREW', NULL, TRUE),
    ('CREW_MONKEY', '원숭이', 'CREW', NULL, TRUE),
    ('PIRATE_PARROT', '앵무새', 'PIRATE', 'WATCH_ACTION', TRUE);

ALTER TABLE room_players ADD COLUMN shown_role_code VARCHAR(60) REFERENCES roles(code); -- 원숭이 위장 직업
ALTER TABLE room_players DROP COLUMN remaining_uses; -- 남은 횟수는 이제 room_actions 개수로 계산
ALTER TABLE rooms ADD COLUMN winner_faction VARCHAR(20); -- 승리 진영(끝나기 전엔 NULL)

-- 기존 밤 행동이 있다면 라운드/단계를 보존한다.
ALTER TABLE room_actions ADD COLUMN phase VARCHAR(20) NOT NULL DEFAULT 'NIGHT'; -- 기존 행은 모두 밤 행동으로 간주
ALTER TABLE room_actions ADD COLUMN round_number INTEGER NOT NULL DEFAULT 0;   -- 일단 0으로 만들고
UPDATE room_actions SET round_number = night_number;                          -- 옛 밤 번호를 복사
ALTER TABLE room_actions DROP CONSTRAINT uq_action_night;  -- 옛 제약(밤마다 1번, 능력 무관) 제거 → 컬럼을 지우기 전에 먼저
ALTER TABLE room_actions DROP COLUMN night_number;         -- 옛 컬럼 제거
-- 새 제약: 같은 사람·단계·라운드·능력 조합은 한 번만 (낮 능력과 밤 능력을 따로 셀 수 있게)
ALTER TABLE room_actions ADD CONSTRAINT uq_action_actor_phase
    UNIQUE (room_id, actor_player_id, phase, round_number, action_code);

-- 수신자별 보고 테이블
CREATE TABLE room_reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- PK(발생 순서)
    room_id BIGINT NOT NULL REFERENCES rooms(id),           -- 방 외래키
    recipient_player_id BIGINT NOT NULL,                    -- 받는 사람 playerId
    round_number INTEGER NOT NULL,                          -- 라운드
    type VARCHAR(60) NOT NULL,                              -- 보고 종류
    message VARCHAR(500) NOT NULL                           -- 내용
    -- ⚠ (room_id, recipient_player_id) 조회용 인덱스가 없다
);
