-- [파일 역할] Flyway 3번 마이그레이션: 해적 공격을 "투표"에서 "공유 대상 선택(변경 가능)"으로 바꾼다.
-- 원본 위치: server/src/main/resources/db/migration/V3__pirate_shared_attack_target.sql

-- 마피아42의 공유 대상 선택처럼 해적이 밤 동안 목표를 다시 고를 수 있게 한다.
-- V1/V2는 적용된 DB의 체크섬을 유지해야 하므로 수정하지 않는다.
UPDATE roles SET action_code = 'SELECT_ATTACK_TARGET' WHERE code = 'PIRATE_RAIDER'; -- 해적 능력 교체

-- 선택 이력 테이블. room_actions와 달리 "밤마다 한 번" 제약이 없어 여러 줄을 쌓을 수 있다.
CREATE TABLE pirate_attack_selections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- 증가하는 PK = 선택 순서
    room_id BIGINT NOT NULL REFERENCES rooms(id),           -- 방 외래키
    night_number INTEGER NOT NULL,                          -- 몇 번째 밤
    actor_player_id BIGINT NOT NULL,                        -- 고른 해적
    request_id UUID NOT NULL,                               -- 재시도 판별용
    target_player_id BIGINT NOT NULL,                       -- 공격 대상
    CONSTRAINT uq_pirate_attack_request UNIQUE (room_id, actor_player_id, request_id) -- 같은 요청 중복 저장 금지
);

-- "이 방 이 밤의 가장 최근 선택"(ORDER BY id DESC LIMIT 1)을 빠르게 찾기 위한 인덱스
CREATE INDEX idx_pirate_attack_latest
    ON pirate_attack_selections (room_id, night_number, id);
