-- 공개 직업 사전. 새 직업은 추후 V2 등 새 Flyway 마이그레이션으로 추가한다.
CREATE TABLE roles (
    code VARCHAR(60) PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    faction VARCHAR(20) NOT NULL,
    action_code VARCHAR(40)
);

CREATE TABLE rooms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phase VARCHAR(20) NOT NULL,
    night_number INTEGER NOT NULL
);

-- user_id는 계정 ID, player_id는 방에서만 유효한 플레이어 번호다.
CREATE TABLE room_players (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id BIGINT NOT NULL REFERENCES rooms(id),
    user_id BIGINT NOT NULL,
    player_id BIGINT NOT NULL,
    role_code VARCHAR(60) REFERENCES roles(code),
    alive BOOLEAN NOT NULL,
    remaining_uses INTEGER NOT NULL,
    CONSTRAINT uq_room_user UNIQUE (room_id, user_id),
    CONSTRAINT uq_room_player UNIQUE (room_id, player_id)
);

-- request_id 재시도와 night_number당 한 번 제출을 DB 제약으로도 보장한다.
CREATE TABLE room_actions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id BIGINT NOT NULL REFERENCES rooms(id),
    actor_player_id BIGINT NOT NULL,
    night_number INTEGER NOT NULL,
    request_id UUID NOT NULL,
    action_code VARCHAR(40) NOT NULL,
    target_player_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL,
    CONSTRAINT uq_action_request UNIQUE (room_id, actor_player_id, request_id),
    CONSTRAINT uq_action_night UNIQUE (room_id, actor_player_id, night_number)
);

INSERT INTO roles (code, name, faction, action_code) VALUES
    ('CREW_CAPTAIN', '선장', 'CREW', NULL),
    ('CREW_DOCTOR', '선의', 'CREW', 'PROTECT'),
    ('CREW_LOOKOUT', '망루지기', 'CREW', NULL),
    ('CREW_BOATSWAIN', '갑판장', 'CREW', NULL),
    ('CREW_GUNNER', '총잡이', 'CREW', NULL),
    ('CREW_DRUNK', '주정뱅이', 'CREW', NULL),
    ('CREW_GHOST', '유령 선원', 'CREW', NULL),
    ('PIRATE_RAIDER', '해적', 'PIRATE', NULL),
    ('PIRATE_KRAKEN', '크라켄', 'PIRATE', NULL),
    ('PIRATE_SPY', '스파이', 'PIRATE', NULL),
    ('NEUTRAL_MONKEY', '원숭이', 'NEUTRAL', NULL);
