-- 보류 직업은 기존 참조를 보존하면서 새 게임의 직업 목록에서 제외한다.
ALTER TABLE roles ADD COLUMN enabled BOOLEAN NOT NULL DEFAULT TRUE;
UPDATE roles SET enabled = FALSE WHERE code IN
    ('PIRATE_KRAKEN', 'PIRATE_SPY', 'CREW_GHOST', 'NEUTRAL_MONKEY');

UPDATE roles SET action_code = 'INVESTIGATE_FACTION' WHERE code = 'CREW_CAPTAIN';
UPDATE roles SET action_code = 'WATCH_VISITORS' WHERE code = 'CREW_LOOKOUT';
UPDATE roles SET action_code = 'BLOCK' WHERE code = 'CREW_BOATSWAIN';
UPDATE roles SET name = '포수', action_code = 'DAY_SHOOT' WHERE code = 'CREW_GUNNER';
UPDATE roles SET action_code = 'READ_CORPSE_ROLE' WHERE code = 'CREW_DRUNK';
UPDATE roles SET action_code = 'TEAM_ATTACK_VOTE' WHERE code = 'PIRATE_RAIDER';

INSERT INTO roles (code, name, faction, action_code, enabled) VALUES
    ('CREW_SAILOR', '일반 선원', 'CREW', NULL, TRUE),
    ('CREW_MONKEY', '원숭이', 'CREW', NULL, TRUE),
    ('PIRATE_PARROT', '앵무새', 'PIRATE', 'WATCH_ACTION', TRUE);

ALTER TABLE room_players ADD COLUMN shown_role_code VARCHAR(60) REFERENCES roles(code);
ALTER TABLE room_players DROP COLUMN remaining_uses;
ALTER TABLE rooms ADD COLUMN winner_faction VARCHAR(20);

-- 기존 밤 행동이 있다면 라운드/단계를 보존한다.
ALTER TABLE room_actions ADD COLUMN phase VARCHAR(20) NOT NULL DEFAULT 'NIGHT';
ALTER TABLE room_actions ADD COLUMN round_number INTEGER NOT NULL DEFAULT 0;
UPDATE room_actions SET round_number = night_number;
ALTER TABLE room_actions DROP CONSTRAINT uq_action_night;
ALTER TABLE room_actions DROP COLUMN night_number;
ALTER TABLE room_actions ADD CONSTRAINT uq_action_actor_phase
    UNIQUE (room_id, actor_player_id, phase, round_number, action_code);

CREATE TABLE room_reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id BIGINT NOT NULL REFERENCES rooms(id),
    recipient_player_id BIGINT NOT NULL,
    round_number INTEGER NOT NULL,
    type VARCHAR(60) NOT NULL,
    message VARCHAR(500) NOT NULL
);
