-- 마피아42의 공유 대상 선택처럼 해적이 밤 동안 목표를 다시 고를 수 있게 한다.
-- V1/V2는 적용된 DB의 체크섬을 유지해야 하므로 수정하지 않는다.
UPDATE roles SET action_code = 'SELECT_ATTACK_TARGET' WHERE code = 'PIRATE_RAIDER';

CREATE TABLE pirate_attack_selections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id BIGINT NOT NULL REFERENCES rooms(id),
    night_number INTEGER NOT NULL,
    actor_player_id BIGINT NOT NULL,
    request_id UUID NOT NULL,
    target_player_id BIGINT NOT NULL,
    CONSTRAINT uq_pirate_attack_request UNIQUE (room_id, actor_player_id, request_id)
);

CREATE INDEX idx_pirate_attack_latest
    ON pirate_attack_selections (room_id, night_number, id);
